name: CI

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        node: [20]

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
      with:
        node-version: '20'

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node }}
        check-latest: true

    - name: Install dependencies
      run: npm install

    - name: Fix permissions
      if: runner.os == 'macOS' || runner.os == 'Linux'
      run: chmod +x ./node_modules/.bin/jest

    - name: Run tests
      run: npm test

    - name: Report test results
      if: failure()
      run: echo "Some tests failed on ${{ matrix.os }} with Node.js ${{ matrix.node }}"
